### PR TITLE
feat: Add session to SSR

### LINKED ISSUE #57: Session are not available on server side rendering
### Environment

```
Nuxt project info:                                                                                                                                                                                                                                                               19:11:34

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.24.3`
- Builder:          `vite`
- User Config:      `srcDir`, `telemetry`, `css`, `modules`, `app`, `runtimeConfig`, `vite`, `session`
- Runtime Modules:  `@groufr/muffins-nuxt@0.1.0`, `@pinia/nuxt@0.4.6`, `@sidebase/nuxt-session@0.2.6`
- Build Modules:    `-`
------------------------------
```

### Reproduction

```vue
<script setup>
const { session, update } = await useSession()

const value = ref('')
watch(session, (s) => {
    console.log('session value :', s)
    if (s.value)
        value.value = s.value
}, { immediate: true })
watch(value, async (value) => {
    await update({ value })
})
</script>

<template>
    <input v-model="value" />
</template>
```

https://stackblitz.com/edit/github-e43zzb?file=app.vue

If you type something in the input and refresh the page, the server will not know about the session that was updated, thus preventing doing server side rendering without node mismatch.

### Describe the bug

I'd like to access my sessions in my root `app.vue` file :

If I run this code, it works well on client side. However on server side the value of the session is always empty.
Can I access the data on server side so I can do proper server side rendering ?

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by mlutsiuk**
Closes #57.

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] manually checked my feature / checking not applicable
- [ ] wrote tests / testing not applicable
- [x] attached screenshots / screenshot not applicable

### CODE REVIEW

**Comment by erossdev** [comment]
+1 thanks mlutsiuk for your work on this

**Review by bobaoapae — APPROVED** [review]
Thanks

**Comment by agracia-foticos** [comment]
Please merge this feature!

**Comment by zoey-kaiser** [comment]
Hi everyone, we are currently in the process of depricating nuxt-session as the native [`h3`](https://github.com/unjs/h3#session) session support case out since the release of this module. 

I can still look to merge and release this PR, however it will be the last and support for this module will end then. 

You can read more about the reasons for this here: https://github.com/sidebase/nuxt-session/issues/91

**Comment by agracia-foticos** [comment]
> Hi everyone, we are currently in the process of depricating nuxt-session as the native [`h3`](https://github.com/unjs/h3#session) session support case out since the release of this module.
> 
> I can still look to merge and release this PR, however it will be the last and support for this module will end then.
> 
> You can read more about the reasons for this here: #91

Please, merge and launch the release

**Review by zoey-kaiser — APPROVED** [review]

**Comment by agracia-foticos** [comment]
Can you generate new release with all pending features?

**Comment by zoey-kaiser** [comment]
I merged and released this PR in https://github.com/sidebase/nuxt-session/releases/tag/0.2.8

**Pull request merged**
